export {default as BannerImage} from './rudraksh_banner.png';
export { default as Logo } from './Logo_Rudraksh.png';
export { default as ProfilePic } from './rudrakshpic.png';
export { default as ProjectImage } from './projectImage.png';
export { default as ProjectImage1 } from './projectImage2.png';
export { default as ProjectImage2 } from './projectImage3.png';
export { default as ProjectImage3 } from './projectImage4.png';
export { default as ProjectImage4 } from './projectImage5.png';
export { default as ProjectImage5 } from './projectImage6.png';
export { default as FigmaBackground } from './figma_background.png';
export { default as AdobeBackground } from './adobe-background.png';
export { default as WebflowBackground } from './webflow_background.png';
export { default as SketchBackground } from './sketch_background.png';
export { default as FramerBackground } from './franer.png';
export { default as CatchMe } from './catchme_img.png';
export { default as FramerIcon } from './framer_icon.png';
export { default as AllInBets } from './All in bets.jpg';
export { default as Affice } from './Affice.jpg';